-- 교환/구매품 테이블 생성 + RLS 정책 + 권한 부여
-- Supabase SQL Editor에서 이 파일 내용을 통째로 붙여넣고 Run 하세요.

create table public.trades (
  id bigint generated by default as identity primary key,
  town text not null,
  npc text not null,
  item_name text not null,
  item_qty integer not null default 1,
  required_name text,
  required_qty integer,
  limit_text text
);

create table public.purchases (
  id bigint generated by default as identity primary key,
  town text not null,
  npc text not null,
  item_name text not null,
  price_currency text,
  price_amount integer,
  limit_text text
);

alter table public.trades enable row level security;
alter table public.purchases enable row level security;

create policy "public read trades" on public.trades for select using (true);
create policy "public read purchases" on public.purchases for select using (true);

create policy "auth insert trades" on public.trades for insert to authenticated with check (true);
create policy "auth update trades" on public.trades for update to authenticated using (true) with check (true);
create policy "auth delete trades" on public.trades for delete to authenticated using (true);

create policy "auth insert purchases" on public.purchases for insert to authenticated with check (true);
create policy "auth update purchases" on public.purchases for update to authenticated using (true) with check (true);
create policy "auth delete purchases" on public.purchases for delete to authenticated using (true);

grant select on public.trades, public.purchases to anon, authenticated;
grant insert, update, delete on public.trades, public.purchases to authenticated;
